### PR TITLE
Add basic unit test suite

### PR DESCRIPTION
**Pull request by rexxars**
This PR adds a basic unit test suite. Some tests are better than no tests.

### CODE REVIEW

**Comment by marco-c** [comment]
To build Node v4 on Travis, you need to install g++-4.8. See, for example, https://github.com/mozilla/oghliner/pull/88.

**Comment by rexxars** [comment]
With this in mind, would it perhaps be better to use node-rsa, instead? I don't expect this will be used in high-performance scenarios anyway?

**Comment by rexxars** [comment]
Nevermind. For now this feels too risky, as I have not added tests that actually verify the output is valid. Will install g++-4.8 instead.

**Comment by marco-c** [comment]
> Nevermind. For now this feels too risky, as I have not added tests that actually verify the output is valid. Will install g++-4.8 instead.

Yes, indeed.
`ursa` seems also more reliable, since it's using OpenSSL, which is well tested, instead of the jsbn library (http://www-cs-students.stanford.edu/~tjw/jsbn/).
I had some issues with jsbn in the past with another project: https://github.com/mozilla/pluotsorbet/pull/159

**Pull request merged**
