### PR TITLE
Update ursa dependency to 0.9.1 to support Node.js v4

### PR DESCRIPTION
**Pull request by marco-c**

### CODE REVIEW

**Comment by marco-c** [comment]
This is an alternative to https://github.com/pwmckenna/node-travis-encrypt/pull/12.

**Comment by rexxars** [comment]
Thanks!

**Comment by marco-c** [comment]
You're welcome! Could you publish a new `travis-encrypt` package? We're using it in `oghliner` (https://github.com/mozilla/oghliner) and to support Node v4 we currently need to install the package from my fork.

**Comment by rexxars** [comment]
I'd love to, but I don't have access to publish on npm. Maybe @pwmckenna would allow me to do that as well? :-)

**Comment by MoOx** [comment]
Any idea when this will be released since in the master already?

**Comment by rexxars** [comment]
I just got `npm publish`-rights and have published 1.1.2.

**Comment by MoOx** [comment]
Nice, thanks!

**Pull request merged**
