### PR TITLE
change ursa to node-rsa

### PR DESCRIPTION
**Pull request by rstacruz**
ursa is not compatible with node.js 4.0. See #11.

this hasn't been tested too thoroughly.

### CODE REVIEW

**Comment by rstacruz** [comment]
oh and it looks like travis is set up in this repo but there's no way to test it.. haha

**Comment by rstacruz** [comment]
@pwmckenna I can merge this, but I can't push it to npm by the way.

**Comment by MoOx** [comment]
+1 for this.

**Comment by pwmckenna** [comment]
merging in master (which has the travis sudo update) seems to have sorted out the build. I'm happy to merge this in if someone has tested the whole cycle of something encrypted with it and can vouch for it. @rstacruz thanks for the work on this!

**Comment by pwmckenna** [comment]
@rstacruz added you as an owner on npm, so feel free to merge/publish :)

**Comment by marco-c** [comment]
Note that we've used the library behind node-rsa (http://www-cs-students.stanford.edu/~tjw/jsbn/) in our project (https://github.com/mozilla/pluotsorbet) and it did suffer from correctness problems.

To overcome the correctness problems, we've had to use it in a non-standard way.

https://github.com/pwmckenna/node-travis-encrypt/pull/17#issuecomment-149911411

**Comment by rexxars** [comment]
I'm a bit skeptical to merging this, based on experiences from @marco-c - especially since I'm not sure how to properly write tests to uncover any problems. Until we get more requests for a better experience on windows, I think we should put this on hold. Closing.

**Pull request closed without merging**
